# Generated by Django 5.2.9 on 2025-12-28 22:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectYouTubeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials_json', models.TextField(verbose_name='OAuth credentials (JSON)')),
                ('channel_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Channel ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'YouTube проекта',
                'verbose_name_plural': 'YouTube проекта',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'indexes': [models.Index(fields=['name'], name='users_categ_name_bcdc62_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание курса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.category', verbose_name='Категория')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('video_limit', models.PositiveIntegerField(default=0, verbose_name='Лимит видео')),
                ('used_videos', models.PositiveIntegerField(default=0, verbose_name='Использовано видео')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='users.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к курсу',
                'verbose_name_plural': 'Доступы к курсам',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('video_url', models.URLField(blank=True, default='', verbose_name='Ссылка на видео')),
                ('youtube_video_id', models.CharField(blank=True, default='', max_length=32, verbose_name='YouTube videoId')),
                ('youtube_status', models.CharField(choices=[('idle', 'Не загружается'), ('uploading', 'Загрузка'), ('processing', 'Обработка YouTube'), ('ready', 'Готово'), ('error', 'Ошибка')], default='idle', max_length=12, verbose_name='Статус YouTube')),
                ('youtube_error', models.TextField(blank=True, default='', verbose_name='Ошибка YouTube')),
                ('video_duration', models.DurationField(blank=True, null=True, verbose_name='Длительность видео')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание урока')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Кто архивировал')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Ответ / ссылка на ДЗ')),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('rework', 'На доработку'), ('declined', 'Отклонено')], default='rework', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='users.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='LessonOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_lessons', to='users.courseaccess', verbose_name='Доступ')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='users.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Открытый урок',
                'verbose_name_plural': 'Открытые уроки',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('limit_type', models.CharField(choices=[('count', 'Кол-во видео'), ('percent', 'Процент от курса'), ('all', 'Все видео курса')], default='count', max_length=10, verbose_name='Тип лимита')),
                ('limit_value', models.PositiveIntegerField(default=0, help_text='count: число видео; percent: 1..100; all: можно 0', verbose_name='Значение лимита')),
                ('video_limit', models.PositiveIntegerField(default=0, editable=False, verbose_name='Итоговый лимит')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='users.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='users.tariff', verbose_name='Тариф'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='users_cours_categor_ec84d0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='users_cours_instruc_3b474f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='users_cours_title_524127_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'is_archived'], name='users_lesso_course__8631e1_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['youtube_status'], name='users_lesso_youtube_7e94d5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['title'], name='users_lesso_title_42b609_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['user', 'lesson'], name='users_homew_user_id_4fdc51_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['status'], name='users_homew_status_e59248_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['created_at'], name='users_homew_created_3ef30c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonopen',
            index=models.Index(fields=['access'], name='users_lesso_access__94cc38_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonopen',
            index=models.Index(fields=['lesson'], name='users_lesso_lesson__704335_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonopen',
            constraint=models.UniqueConstraint(fields=('access', 'lesson'), name='uniq_open_access_lesson'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['course'], name='users_tarif_course__8a48a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['limit_type'], name='users_tarif_limit_t_a97c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['user', 'course'], name='users_cours_user_id_49c6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['token'], name='users_cours_token_02d94a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['is_active'], name='users_cours_is_acti_d3784b_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseaccess',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_user_course_access'),
        ),
    ]
