# Generated by Django 5.2.9 on 2025-12-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_description',
            field=models.TextField(blank=True, default='', verbose_name='ДЗ: описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_file',
            field=models.FileField(blank=True, help_text='PDF/DOCX/ZIP и т.д. (не видео)', null=True, upload_to='homework_files/%Y/%m/%d/', verbose_name='ДЗ: файл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_link',
            field=models.URLField(blank=True, default='', help_text='Ссылка на Google Drive / GitHub / Notion и т.д.', verbose_name='ДЗ: ссылка'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ДЗ: название'),
        ),
    ]
