# Generated by Django 5.2.9 on 2025-12-29 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание (ответ студента)', 'verbose_name_plural': 'Домашние задания (ответы студентов)'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='YouTube: время загрузки'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='users.course'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='users.tariff'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='used_videos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='video_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_link',
            field=models.URLField(blank=True, default='', help_text='Google Drive / GitHub / Notion и т.д.', verbose_name='ДЗ: ссылка'),
        ),
        migrations.AlterField(
            model_name='lessonopen',
            name='access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_lessons', to='users.courseaccess'),
        ),
        migrations.AlterField(
            model_name='lessonopen',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='users.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonopen',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='limit_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Значение лимита'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Формат: +996... (не обязательно)', max_length=32, verbose_name='Номер телефона'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['created_at'], name='users_lesso_created_530430_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'),
        ),
    ]
