# Generated by Django 5.2.9 on 2025-12-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_courseanalytics_coursedailyanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Фото категории'),
        ),
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Фото Курса'),
        ),
    ]
