# Generated by Django 5.2.9 on 2025-12-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_category_photo_course_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('banner', models.ImageField(upload_to='banner/', verbose_name='Фото для баннера')),
                ('whatsapp_number', models.CharField(max_length=100, verbose_name='Номер whatsapp')),
            ],
            options={
                'verbose_name': 'Основные настройки сайта',
                'verbose_name_plural': 'Основные настройки сайта',
            },
        ),
    ]
