# Generated by Django 5.2.9 on 2025-12-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_settingssite'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingssite',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/', verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
