# Generated by Django 5.2.9 on 2026-01-01 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_settingssite_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принято'), ('examination', 'На проверке'), ('rework', 'На доработку'), ('declined', 'Отклонено')], default='rework', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Фото для баннера'),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер whatsapp'),
        ),
    ]
