# Generated by Django 5.2.9 on 2026-01-01 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_courseaccess_user_alter_homework_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseaccess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveConstraint(
            model_name='courseaccess',
            name='uniq_user_course_access',
        ),
        migrations.RemoveIndex(
            model_name='courseaccess',
            name='users_cours_user_id_49c6f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseaccess',
            name='users_cours_token_02d94a_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseaccess',
            name='users_cours_is_acti_d3784b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='courseaccess',
            unique_together={('user', 'course')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше — тем раньше урок', verbose_name='Порядок урока'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tariff'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='video_limit',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='users_lesso_course__5c600a_idx'),
        ),
        migrations.RemoveField(
            model_name='courseaccess',
            name='used_videos',
        ),
    ]
