# Generated by Django 5.2.9 on 2026-01-05 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_courseaccess_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseaccess',
            options={'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступы'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='users_cours_categor_ec84d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='users_cours_instruc_3b474f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='courseaccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принято'), ('examination', 'На проверке'), ('rework', 'На доработку'), ('declined', 'Отклонено')], default='examination', max_length=15, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_archived'], name='users_cours_categor_18b002_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'is_archived'], name='users_cours_instruc_778aae_idx'),
        ),
    ]
