# Generated by Django 5.2.9 on 2026-01-06 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_courseaccess_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseaccess',
            options={'verbose_name': 'Доступ к курсу', 'verbose_name_plural': 'Доступы к курсам'},
        ),
        migrations.AlterModelOptions(
            name='courseanalytics',
            options={'verbose_name': 'Аналитика курса', 'verbose_name_plural': 'Аналитика курсов'},
        ),
        migrations.AlterModelOptions(
            name='coursedailyanalytics',
            options={'ordering': ['-date'], 'verbose_name': 'Дневная аналитика курса', 'verbose_name_plural': 'Дневная аналитика курсов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterUniqueTogether(
            name='coursedailyanalytics',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Фото курса'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='users.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='video_limit',
            field=models.PositiveIntegerField(editable=False, verbose_name='Лимит уроков'),
        ),
        migrations.AlterField(
            model_name='courseanalytics',
            name='completion_rate',
            field=models.FloatField(default=0, verbose_name='Процент прохождения'),
        ),
        migrations.AlterField(
            model_name='courseanalytics',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='users.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseanalytics',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего уроков'),
        ),
        migrations.AlterField(
            model_name='courseanalytics',
            name='total_opens',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего открытий'),
        ),
        migrations.AlterField(
            model_name='courseanalytics',
            name='total_purchases',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего покупок'),
        ),
        migrations.AlterField(
            model_name='courseanalytics',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Общая выручка'),
        ),
        migrations.AlterField(
            model_name='courseanalytics',
            name='total_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего студентов'),
        ),
        migrations.AlterField(
            model_name='courseanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='coursedailyanalytics',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='users.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursedailyanalytics',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='coursedailyanalytics',
            name='homeworks_accepted',
            field=models.PositiveIntegerField(default=0, verbose_name='ДЗ принято'),
        ),
        migrations.AlterField(
            model_name='coursedailyanalytics',
            name='homeworks_submitted',
            field=models.PositiveIntegerField(default=0, verbose_name='ДЗ отправлено'),
        ),
        migrations.AlterField(
            model_name='coursedailyanalytics',
            name='opened_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Открытые уроки'),
        ),
        migrations.AlterField(
            model_name='coursedailyanalytics',
            name='purchases',
            field=models.PositiveIntegerField(default=0, verbose_name='Покупки'),
        ),
        migrations.AlterField(
            model_name='coursedailyanalytics',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='coursedailyanalytics',
            name='unique_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Уникальные студенты'),
        ),
        migrations.AlterField(
            model_name='lessonopen',
            name='access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_lessons', to='users.courseaccess', verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='lessonopen',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='users.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lessonopen',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Открыт'),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер WhatsApp'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['user'], name='users_cours_user_id_55526e_idx'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['course'], name='users_cours_course__3b20a3_idx'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['created_at'], name='users_cours_created_52ed01_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonopen',
            index=models.Index(fields=['opened_at'], name='users_lesso_opened__0f7901_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseaccess',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_access_user_course'),
        ),
        migrations.AddConstraint(
            model_name='coursedailyanalytics',
            constraint=models.UniqueConstraint(fields=('date', 'course'), name='uniq_daily_date_course'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_homework_user_lesson'),
        ),
    ]
